bot:
  token: MTMwODQ5Njc0ODU0MDMzMDAzNA.G4tCnf.MNBkONTxVbEGB7zYqDHVZS0wBwFlq6nl7J8kVA
  owner_ids:
    - 860776210438946836
  prefix: $
  default_bet: 100
  bonus_multiplier: 5  # bonus = default_bet * multiplier
  bonus_cooldown: 12  # Bonus every 12 hours
